# Generated by Django 3.2.3 on 2021-06-06 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_curriculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.CharField(max_length=80)),
                ('site', models.CharField(max_length=80)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_curriculo.candidato')),
            ],
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
