# Generated by Django 3.2.3 on 2021-06-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_curriculo', '0002_auto_20210606_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='foto',
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto_candidato',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
