# Generated by Django 3.2.3 on 2021-06-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_curriculo', '0003_auto_20210610_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacao',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='habilidades',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='objetivos',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
