# Generated by Django 3.2.3 on 2021-06-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_curriculo', '0004_auto_20210614_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formacao',
            old_name='descricao',
            new_name='descricaofor',
        ),
        migrations.RenameField(
            model_name='habilidades',
            old_name='descricao',
            new_name='descricaohab',
        ),
        migrations.RenameField(
            model_name='objetivos',
            old_name='descricao',
            new_name='descricaoobj',
        ),
    ]
