# Generated by Django 3.2.3 on 2021-06-21 19:15

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_curriculo', '0005_auto_20210621_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='foto_candidato',
            field=stdimage.models.StdImageField(upload_to='fotos', verbose_name='Imagem'),
        ),
    ]
