# Generated by Django 3.2.3 on 2021-06-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_curriculo', '0006_alter_candidato_foto_candidato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='foto_candidato',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
